---
- hosts: docker-nn
  tasks:
   - name: copy hdfs-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/hdfs-site-nn.xml
        dest: /hadoop2/etc/hadoop/hdfs-site.xml

   - name: copy core-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/core-site.xml
        dest: /hadoop2/etc/hadoop/core-site.xml

   - name: format namenode
     command: hadoop namenode -format

   - name: starting namenode
     shell: hadoop-daemon.sh start namenode

- hosts: docker-jt
  tasks:
   - name: copy core-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/core-site.xml
        dest: /hadoop2/etc/hadoop/core-site.xml

   - name: copy mapred-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/mapred-site-jt.xml
        dest: /hadoop2/etc/hadoop/mapred-site.xml

   - name: starting jobtracker
     shell: hadoop-daemon.sh start jobtracker

- hosts: docker-dn
  tasks:
   - name: copy hdfs-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/hdfs-site-dn.xml
        dest: /hadoop2/etc/hadoop/hdfs-site.xml

   - name: copy core-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/core-site.xml
        dest: /hadoop2/etc/hadoop/core-site.xml

   - name: copy mapred-site 
     copy:
        src: /root/Hadoop-Project/source_files/docker_hv1/mapred-site.xml
        dest: /hadoop2/etc/hadoop/mapred-site.xml

   - name: starting services
     shell: hadoop-daemon.sh start datanode ; hadoop-daemon.sh start tasktracker